name: Test whether it compiles with various compilers

on:
  pull_request:
    branches:
    - main
    - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      max-parallel: 5
      matrix:
        cuda-version: ['12.6', '13.0', '13.2']
        pytorch-version: ['2']
        include:
          - gxx-version: '12'
            cuda-version: '12.6'
            arch-list: "5.0;6.0;7.0;8.0;9.0"
          - gxx-version: '14'
            cuda-version: '13.0'
            arch-list: "8.0;9.0;10.0;12.0"
          - gxx-version: '14'
            cuda-version: '13.2'
            arch-list: "8.0;9.0;10.0;12.0"
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
    - name: Install dependencies
      run: >
        CONDA_OVERRIDE_CUDA=${{ matrix.cuda-version }}
        conda create
        --quiet
        -n torch
        -c conda-forge
        --solver=libmamba
        cuda-version=${{ matrix.cuda-version }}
        pytorch-gpu=${{ matrix.pytorch-version }}
        gcc_linux-64=${{ matrix.gxx-version }}
        gxx_linux-64=${{ matrix.gxx-version }}
        cuda-nvcc_linux-64=${{ matrix.cuda-version }}
        cuda-cudart-dev
        libcurand-dev
        scipy
        numpy
        pip
        setuptools
        ninja
        cmake
        setuptools-scm
        setuptools
        toml
    - name: Build torch-radon
      run: |
        conda activate torch
        which python
        gcc --version
        g++ --version
        nvcc --version
        export TORCH_CUDA_ARCH_LIST="${{ matrix.arch-list }}"
        pip install . -vv --no-deps --no-build-isolation --no-index
    - name: Test dependencies
      run: |
        conda activate torch
        pip check
